# Generated by Django 4.2.2 on 2023-09-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='uupdated_at',
            new_name='updated_at',
        ),
    ]
