# Generated by Django 4.2.2 on 2023-10-05 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='login_and_registration_app.user'),
            preserve_default=False,
        ),
    ]
